version: '3.8'

services:
  api:
    container_name: api
    build: .
    command: npm run start:dev
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: postgres_${MODE}
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata_${MODE}:/var/lib/postgresql/data_${MODE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
